version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: tu_usuario
      POSTGRES_PASSWORD: tu_password
      POSTGRES_DB: tu_base_de_datos
    volumes:
      - ./data_base:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

    ports:
      - "5432:5432"
    restart: always
  app:
    image: openjdk:21-jdk-slim
    container_name: my_java_app
    volumes:
      - ./futsal-back-0.0.1-SNAPSHOT.jar:/app/app.jar  # Cambia esta ruta por la ubicación real de tu archivo .jar
    command: ["java", "-jar", "/app/app.jar"]
    ports:
      - "80:8082"  # Cambia 8080 al puerto donde tu aplicación escucha internamente
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/tu_base_de_datos
